clean up compiler warnings

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,19 +1,35 @@
 #!/bin/sh
 
+OMIT_WARNINGS=true
+
 : ${R_HOME=`R RHOME`}
 if test -z "${R_HOME}" ; then
-    echo "could not determin R_HOME"
+    echo "could not determine R_HOME"
     exit 1
 fi
 
+
 # use deprecated CXX1X* to support R versions 3.1.0 to 3.3.3
 CXX11=`"${R_HOME}/bin/R" CMD config CXX1X`
+# echo $CXX11
 CXX11STD=`"${R_HOME}/bin/R" CMD config CXX1XSTD`
+# echo $CXX11STD
 CXX="${CXX11} ${CXX11STD}"
+# echo $CXX
 CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXX1XFLAGS`
+# echo $CXXFLAGS
 
 AF_CXXFLAGS=`${R_HOME}/bin/Rscript -e "RcppArrayFire:::CxxFlags()"`
 AF_LIBS=`${R_HOME}/bin/Rscript -e "RcppArrayFire:::LdFlags()"`
+
+# echo $AF_CXXFLAGS
+# 
+# if $OMIT_WARNINGS; then
+#   AF_CXXFLAGS=AF_CXXFLAGS+" -Wswitch -Wunused-function -Wgnu-anonymous-struct"
+#   exit 1
+# fi
+# 
+# echo $AF_CXXFLAGS
 
 sed -e "s|@AF_LIBS@|${AF_LIBS}|" \
     -e "s|@AF_CXXFLAGS@|${AF_CXXFLAGS}|" \
